### ISSUE TITLE
geo heat map does not work 

### ISSUE THREAD

**Issue by Himmetk** [rakam-io/rakam-ui#100]

**Comment by buremba** [comment]
i couldn't reproduce it, what's the problem?

**Comment by Himmetk** [comment]
try turn this to geo heat map: https://app.rakam.io/84/reports/users_opened_bounty_app?country=208
or any report with lat long.
I would strongly recommend to use google'a API for heat map : 
https://developers.google.com/maps/documentation/javascript/examples/layer-heatmap

**Comment by buremba** [comment]
Fixed
