### ISSUE TITLE
Event explorer dimension is set to hour, but results of the same are on half hourly basis

### ISSUE THREAD

**Issue by RameshByndoor** [rakam-io/rakam-ui#108]
Also the timezone is shifted by IST in our case.

<img width="1222" alt="screen shot 2017-07-06 at 12 09 26 pm" src="https://user-images.githubusercontent.com/3341964/29059843-e435c48c-7c34-11e7-9fd8-28de669702b8.png">

**Comment by buremba** [comment]
I reimported the event explorer summary table, I don't know how we ended up wrong values in that table but I will inspect and let you know if the bug occurs again.
