### ISSUE TITLE
In Event explorer view, data is listed in Others Column based on some ranking which is not set by user.

### ISSUE THREAD

**Issue by arindams** [rakam-io/rakam-ui#109]
Based on the below case ,
   User is expecting data to be displayed only in app_launch_v1 column.
   At present based on some ranking few of the data is part of app_launch_v1 , rest is part of "Others".
   The others column is  not required
<img width="996" alt="screen shot 2017-08-01 at 10 04 25 pm" src="https://user-images.githubusercontent.com/8611265/29179951-c5aac5ae-7e13-11e7-8b88-26fa6a9f1c3b.png">

**Comment by buremba** [comment]
The bug is fixed in latest version.
