### ISSUE TITLE
Explorer view has options to create reports , bur no option to delete or update

### ISSUE THREAD

**Issue by arindams** [rakam-io/rakam-ui#110]
<img width="1169" alt="screen shot 2017-08-07 at 1 07 56 pm" src="https://user-images.githubusercontent.com/8611265/29180165-8c49b436-7e14-11e7-9906-fcca4d8ac599.png">

**Comment by buremba** [comment]
Our latest version has support for deleting the reports. When you click one of them, you will see the three dots icon similar to funnel section.
