### ISSUE TITLE
Explorer view, Bar chart is not plotted

### ISSUE THREAD

**Issue by arindams** [rakam-io/rakam-ui#112]
In explorer view,
Select a collection and some dimension and try to plot data as bar chart.
Issue is , it is not able to plot the data in barchart format.

<img width="1326" alt="screen shot 2017-08-10 at 10 01 59 pm" src="https://user-images.githubusercontent.com/8611265/29181120-9e34d6e6-7e17-11e7-823a-d7cd2e0edd89.png">

**Comment by buremba** [comment]
Fixed, thanks for reporting.
P.S: Are you using any application similar to [Flux](https://justgetflux.com/)? The color of the screen should be darker and it has green tones than it is in the screenshot that you sent.
