### ISSUE TITLE
Report View,Editing of sort mode doesn't take into affect.

### ISSUE THREAD

**Issue by arindams** [rakam-io/rakam-ui#113]
Create a report on a specific collection.
Add a filter.
Add a measure.
Add a group by.
Keep sort as Ascending on the measure column.
Run and save the report.
Reopen the report , click on run.
Update sort mode to Descending now.
Click on run the results displayed is still in ascending sort order. Save the report .
Reopen the report, the sort order is set to ascending.

**Comment by buremba** [comment]
Fixed.
