### ISSUE TITLE
Adding member to a project in rakam ui should not be case sensitive

### ISSUE THREAD

**Issue by engineerkarthikk** [rakam-io/rakam-ui#115]
User id should not be case sensitive. If added same user id in both capital and small letters, it is treating it as two different users which leads to adding duplicate users with different permissions. 
<img width="940" alt="duplicate_user" src="https://user-images.githubusercontent.com/13032361/30095442-5cf059ce-92f0-11e7-8cd2-308d4484ccfc.png">

**Comment by buremba** [comment]
Fixed the bug in master. Thanks for reporting!

**Comment by engineerkarthikk** [comment]
Assume added 'testuser@olacabs.com' user into rakam project with read permission, 
i. Able to add the same user 'testuser@olacabs.com' with different permission 
ii. Also able to add the same user with different case 'TESTUSER@OLACABS.COM' with different permission

**Comment by buremba** [comment]
It looks like I forgot to push the changes to repo, could you please deploy the latest version and try again?
