### ISSUE TITLE
Parameters UX Fail

### ISSUE THREAD

**Issue by Himmetk** [rakam-io/rakam-ui#119]
I still got this kind of screenshots from my colleagues.
![screen shot 2017-09-25 at 13 04 45](https://user-images.githubusercontent.com/24540700/30803409-2825df82-a1f2-11e7-93e5-948dc9381ebb.png)

**Comment by Himmetk** [comment]
also limit for string parameters is not sufficient for us now should be more than 1000.

**Comment by buremba** [comment]
Fixed
