### ISSUE TITLE
Values not Populating in filter builder

### ISSUE THREAD

**Issue by engineerkarthikk** [rakam-io/rakam-ui#123]
Auto suggesting values for filter is not populating.

<img width="618" alt="autosuggestion" src="https://user-images.githubusercontent.com/13032361/33205218-2375eb4e-d12c-11e7-894a-965a2fdcc375.png">

**Comment by rajivonat** [comment]
@buremba @kazim-i We need a fix for this by weekend. Please let us know if any questions

**Comment by buremba** [comment]
It looks like your deployment includes the latest version of UI but the API part is not updated. Here is how it should look like: 
<img width="455" alt="screen shot 2017-11-24 at 5 26 25 am" src="https://user-images.githubusercontent.com/82745/33212488-32cef2ce-d0d8-11e7-9f13-7c28d34a359a.png">

I talked with @ramesh.byndoor and once we deploy the latest version, it should work fine.
