### ISSUE TITLE
Not able to groupby by time in Funnel Query

### ISSUE THREAD

**Issue by engineerkarthikk** [rakam-io/rakam-ui#124]
Specify funnel steps and try to groupby by time, it is showing 
<img width="1132" alt="groupby _time" src="https://user-images.githubusercontent.com/13032361/33205592-81618294-d12d-11e7-9b21-be6f606c60a6.png">

**Comment by buremba** [comment]
`_time` dimension should be used with segment. Now it returns a proper error about the segment and the UI us updated. Could you please update Rakam and try again?

**Comment by buremba** [comment]
Fixed.
