### ISSUE TITLE
Adjustable Column Witdh

### ISSUE THREAD

**Issue by Himmetk** [rakam-io/rakam-ui#15]
and for some cases horizontal scrolling would be useful.
![screen shot 2016-12-29 at 12 08 17](https://cloud.githubusercontent.com/assets/24540700/21540237/9dceabb2-cdb6-11e6-9cd7-f8c355d90602.png)

**Comment by buremba** [comment]
horizontal scrolling is already available in tables but it's determined programatically. if the width is not enough to show the values of columns, or if the number of columns is more than a certain value (11 if i remember correctly), the table automatically switches to the horizontal scrolling with fixed dimension values.
