### ISSUE TITLE
Dashboard - Add % on weekly growth

### ISSUE THREAD

**Issue by sercanlir** [rakam-io/rakam-ui#22]
![screen shot 2017-01-28 at 5 55 35 pm](https://cloud.githubusercontent.com/assets/7707160/22397820/017f42f0-e583-11e6-95dc-0664817c32ef.png)
Next to weekly user count, I would like to compare the value to previous week and also to cumulative user count in terms of percentage growth.

**Comment by buremba** [comment]
You can do this with WINDOW functions using SQL.
