### ISSUE TITLE
Dashboard - Reports - Duplicate Current Report

### ISSUE THREAD

**Issue by sercanlir** [rakam-io/rakam-ui#23]
I need to be able to duplicate my current report to make minor changes..
![screen shot 2017-01-28 at 6 52 20 pm](https://cloud.githubusercontent.com/assets/7707160/22398161/f76c8068-e58a-11e6-8d8f-217c558ce3a8.png)

**Comment by buremba** [comment]
you can click the edit button and save it as a new report. we may rename the edit button as `edit & duplicate` but i'm not sure if it makes things complicated..
