### ISSUE TITLE
Dashboard - Save Chart UI

### ISSUE THREAD

**Issue by sercanlir** [rakam-io/rakam-ui#24]
When I adjust size of charts, my dashboard screen does not stay the same way. I want to be able to adjust them and keep that the way I want ;)
![screen shot 2017-01-30 at 10 35 33 am](https://cloud.githubusercontent.com/assets/7707160/22416542/d9fc48f8-e6d7-11e6-810d-67e319f2a45d.png)
![screen shot 2017-01-30 at 10 35 48 am](https://cloud.githubusercontent.com/assets/7707160/22416554/e2b842bc-e6d7-11e6-8d36-3d8aa1e1d00e.png)

**Comment by buremba** [comment]
There is a save button in top bar.
