### ISSUE TITLE
Report list is closed even one report is selected

### ISSUE THREAD

**Issue by Himmetk** [rakam-io/rakam-ui#26]
this snaphot report in "project based reports" group but as you see it is closed and its killing UX
![screen shot 2017-02-10 at 16 57 18](https://cloud.githubusercontent.com/assets/24540700/22829137/13d54448-efb2-11e6-8311-bd64f28c79fd.png)

**Comment by Himmetk** [comment]
problem was solved but now I am having same problem again.

**Comment by buremba** [comment]
I added support for saving the state of report groups, it may be related with the cache because it should be working fine.
