### ISSUE TITLE
tick box to select more than one in  paramaters

### ISSUE THREAD

**Issue by Himmetk** [rakam-io/rakam-ui#27]

**Comment by Himmetk** [comment]
Any update? For example we would like  to choose more than one project id > https://app.rakam.io/dashboard/345

**Comment by Himmetk** [comment]
any update?

**Comment by nurkhz** [comment]
@Himmetk we've been working on iOS SDK and Market Place Recipes as you know. therefore this task is not done yet. it's hold on and we'll get back to you once it's completed. thanks for your patience.

**Comment by buremba** [comment]
@Himmetk it should be available as `select-multiple` as variable type.

**Comment by Himmetk** [comment]
for the static value if label is different than shown multiple string is not working.
![screen shot 2017-03-14 at 11 51 10](https://cloud.githubusercontent.com/assets/24540700/23908695/c2bfb28a-08e5-11e7-9891-eaa9b94f8e50.png)
