### ISSUE TITLE
Live view does not work

### ISSUE THREAD

**Issue by evelant** [rakam-io/rakam-ui#3]
When I enter live view, click subscribe new events, and then generate events from my app they do not show up

**Comment by buremba** [comment]
The deployment type you use is Postgresql and unfortunately Postgresql doesn't have stream processing capabilities. The workaround that I found is to create TRIGGERs at runtime for the collections and attaching them to tables to listen the changes but it doesn't always seem to work. I wrote a fallback module that implements live view in backend side so if you have only one API server,  you will be able to listen the new events without any problem. 

The module can be enabled with `event-stream=server` config, if you just deploy the Heroku app again, it should be installed without any problem.
