### ISSUE TITLE
To show selected metrics on Geo Cluster Map

### ISSUE THREAD

**Issue by Himmetk** [rakam-io/rakam-ui#36]
Now geo cluster map is only count rows by lat long. If we can show there SUM of selected metrics that would be perfect!

**Comment by buremba** [comment]
Isn't it possible to use SQL for this use-case?

**Comment by Himmetk** [comment]
I was not able to do , how? title or color are not functioning as I see.

**Comment by Himmetk** [comment]
any update?

**Comment by nurkhz** [comment]
@Himmetk we've been working on iOS SDK and Market Place Recipes as you know. therefore this task is not done yet. it's hold on and we'll get back to you once it's completed. thanks for your patience.

**Comment by Himmetk** [comment]
?

**Comment by buremba** [comment]
color and title should be working fine right now. i could not understand what you meant with "SUM of selected metrics", could you please share an example?
