### ISSUE TITLE
Unable to use table type "materialized view" when using table name in a report variable

### ISSUE THREAD

**Issue by evelant** [rakam-io/rakam-ui#40]
There seems to be an issue with loading the materialized view names. I was attempting to set up materialized views to substitute into queries to analyze my different segments.

```
TypeError: Cannot read property 'forEach' of undefined
    at Object.x [as processQueryResponse] (services.js:2557)
    at rakam-report.js:365
    at h.$broadcast (angular.min.js:138)
    at create-report.js:981
    at angular.min.js:121
    at h.$eval (angular.min.js:135)
    at h.$digest (angular.min.js:132)
    at h.$apply (angular.min.js:135)
    at HTMLButtonElement.<anonymous> (angular.min.js:259)
    at De (angular.min.js:35)
    at HTMLButtonElement.n (angular.min.js:35)
    at HTMLButtonElement.wrapped (raven.js:372)
```

**Comment by buremba** [comment]
Could you please post the SQL query so that I can reproduce it and identify the bug?

**Comment by evelant** [comment]
```select count(distinct _user) from collection."checked off a task" where _user in (select id from {segment})```

Where {segment} is a string type variable set to table name with table type materialized view. It works fine if I set the table type to collection.

**Comment by buremba** [comment]
That's one of the hidden features of Rakam UI so we don't have enough documentation for it. :) First of all the part `{segment}` must be `materialized.{segment}` and the option "Do not include quotes" must be enabled. Then you should select `custom-report` in `Values` section of the parameter, you will see the `user-segment `custom report and then when you select it, an example custom report will appear.

The last thing is to select the actual value of the parameter in `Value field `section of custom parameter. Since we're using `user-segment`, it should be `table_name` as you may guess when you take a look at the example custom report.

I'm aware that it's complex but my priority was to make Rakam UI flexible as possible (the users can define their own custom reports etc.) but it led to poor UX and complex usage. In fact, this is the main issue that we suffer for the last few months. We will make these parts more user friendly in the future, and we're open to your suggestions!

**Comment by buremba** [comment]
We're having difficulties in our Intercom account. Regarding to your Intercom message, here is my response:

The save segment feature uses materialized views. If you want to use your saved segments, you can reference them as materialized.user_segment_segment_name in SQL queries that you run in report playground page. You should also be able to see the materialized view in sidebar. 

If the segmentation in people page is not enough for you, you create your own segments in report playground page, save as materialized view and reference them similar to what you have done via segments. Does this approach work for you?

**Comment by evelant** [comment]
Yes I discovered that I can save my own materialized views via the report creator. That works great for me.

I am still having problems with simply selecting the name of one of those materialized view in a variable.

When I select "custom-report" with "user-segment" and "table_name" I can only see the materialized views created via the people tab in the dropdown. My custom materialized views created via the report page do not show up. I expected to just select "table name" from the Values section and "materialized view" for the table type but that is what is crashing for me with the stack trace in the browser console 

```
TypeError: Cannot read property 'map' of undefined
    at rakam-report.js:46
    at angular.min.js:121
    at h.$eval (angular.min.js:135)
    at h.$digest (angular.min.js:132)
    at h.$apply (angular.min.js:135)
    at r (angular.min.js:88)
    at m (angular.min.js:93)
    at XMLHttpRequest.w.onload (angular.min.js:94)
    at XMLHttpRequest.wrapped (raven.js:372)
```

**Comment by evelant** [comment]
I really appreciate how flexible you have made the system. It is far more powerful than other solutions. As for how to make it easier to use, I would suggest the following:

- add the SQL editing mode to the People page
- add a variable value to the reports page called "segment" that lets the user pick from the materialized views (segments) created on the People page, simply inserting "materialized.view_name_here" into the query
- add "segment" as an option in the visual query builder for reports. This would just insert "where _user in (select id from materialized.segment_name_here)" to the query

This would IMO make things a lot more clear. All segments, even custom SQL ones, could be created from the People page and there would be a very obvious way to access them in reports.

**Comment by evelant** [comment]
The culprit appears to be line 37 of rakam-report.js

```
$scope.promise = analyticsService.listMaterializedViews().then(function (data) {
                                return data.table_name;
                            });
```

The ```analyticsService.listMaterializedViews()``` promise appears to be returning with ```data.table_name ==  undefined``` instead of the name of the materialized view

**Comment by buremba** [comment]
Thanks a lot for the feedbacks. The inline function was invalid and I fixed it now.

**Comment by evelant** [comment]
This appears to still be broken, has it not been deployed yet?

**Comment by buremba** [comment]
It looks like deploy was cancelled due to an issue in our build system. I fixed it and deployed it again.
