### ISSUE TITLE
Double Axis on Line graph

### ISSUE THREAD

**Issue by Himmetk** [rakam-io/rakam-ui#44]
Its not easy to compare two metrics which are related with each other but huge gap between values with one axis line graph.

**Comment by Himmetk** [comment]
Any update? I need this very often.

**Comment by buremba** [comment]
thanks, it's scheduled to be implemented this week.

**Comment by Himmetk** [comment]
No update yet? Also, it would be awesome to be able to put a target line on bar or line charts. In order to show teams their target level. I think easy but essential improvements.

**Comment by buremba** [comment]
Implemented. See `yAxis` option in column options. Example: http://app.rakam.io/current/report-playground?options=%7B%22chartType%22:%22line%22,%22limit%22:1000,%22enableStatistics%22:true,%22tableOptions%22:%7B%22enabled%22:true%7D,%22chartOptions%22:%7B%7D,%22variables%22:%5B%5D,%22segments%22:%5B%5D,%22measures%22:%5B0,1%5D,%22dimensions%22:%5B%5D,%22columnOptions%22:%5B%7B%22tableOptions%22:%7B%22cellOptions%22:%7B%7D%7D,%22chartOptions%22:%7B%7D%7D,%7B%22tableOptions%22:%7B%22cellOptions%22:%7B%7D%7D,%22chartOptions%22:%7B%22yAxis%22:%22right%22%7D%7D%5D%7D&queryOptions=%7B%7D&query=select%202,%20100%20union%20all%20select%205,%20200
