### ISSUE TITLE
LDAP support for Authentication 

### ISSUE THREAD

**Issue by sambitdixit** [rakam-io/rakam-ui#55]
Many organisations have in-house LDAP where they maintain their username/pwd, group, permissions. It will be good if Rakam provides these features out of box.

**Comment by buremba** [comment]
Added in latest version. Here is an example configuration:
```
{
“authentication”: “ldap”,
“authentication.ldap.url”: “ldap://ldap.forumsys.com:389",
“authentication.ldap.user-bind-pattern”: “cn=read-only-admin,dc=example,dc=com”
}
```
