### ISSUE TITLE
people export only includes around 100 rows

### ISSUE THREAD

**Issue by davidmann4** [rakam-io/rakam-ui#58]
There is no way to export people data to a csv

**Comment by Himmetk** [comment]
you should change your query limit than users can export up to 50K rows csv.

**Comment by davidmann4** [comment]
can you post a screenshot where I can change query limit for users? (Menu item: Peoples)

**Comment by buremba** [comment]
<img width="330" alt="screen shot 2017-05-08 at 5 04 49 pm" src="https://cloud.githubusercontent.com/assets/82745/25830254/7e925422-3410-11e7-81ee-15706bb78448.png">

Hey @davidmann4, did you see the export button in people page?

**Comment by buremba** [comment]
If you select all with the checkbox in header and export as csv, it should export all the data.
