### ISSUE TITLE
show % on piechart when hover on slice near exact numbers

### ISSUE THREAD

**Issue by Himmetk** [rakam-io/rakam-ui#59]

**Comment by buremba** [comment]
I added `show percentage` option to pie charts. Currently it shows the percentage on label and it's usually useful for dashboards.

**Comment by Himmetk** [comment]
legend does not work on pie chart so when I try to show both % and label on chart they are not fit over slice.  If legend work I can only show % as label so they would fit.

**Comment by buremba** [comment]
Added legend feature to pie charts
