### ISSUE TITLE
If you add label to multiple string it does not work

### ISSUE THREAD

**Issue by Himmetk** [rakam-io/rakam-ui#61]
for example,

if  you add static value
1, accepted
2, rejected it does not work. but if you add like 1,2 - 2,2 it  works.

**Comment by Himmetk** [comment]
any update?

**Comment by buremba** [comment]
I couldn't reproduce the bug. Could you please record it via a screen recorder and share it with me?

**Comment by buremba** [comment]
We couldn't reproduce the issue.
