### ISSUE TITLE
Only show selected attributes in filter builder

### ISSUE THREAD

**Issue by buremba** [rakam-io/rakam-ui#64]
While building a funnel, people are currently able to see all columns of a collection as filter dropdown. Some of the columns of a collection may contain values which are large e.g. session_id or event_id which we dont want to show as part of filter dropdown. Instead we want a selected list of columns that should appear as part of all collection filters dropdown. This list could be configured as a comma separated list in custom json that will apply to all collection. Or it could be a comma separated list that will be skipped while showing the filter drop down. This kind of filtering is required for filters beside the funnel collection dropdown and similarly under advanced section for "custom connector field" text box. Because in custom connector field also we want to give specific columns as custom connector to group by.

**Comment by buremba** [comment]
Also add this feature for group by fields

**Comment by sambitdixit** [comment]
Any idea when this feature can be picked up.

**Comment by buremba** [comment]
I'm not sure if this specific feature can be useful among Rakam users. Most of the other analytics services such as Amplitude and Mixpanel doesn't allow you to to disable fields and this is definitely an advanced feature. Since this is an enhancement and you're the only company that wants this feature, I need your help.
