### ISSUE TITLE
group by dropdown redesign in funnel 

### ISSUE THREAD

**Issue by sambitdixit** [rakam-io/rakam-ui#68]
1. Currently the group by dropdown is getting visible only after the first funnel report is built and displayed and then the user will be able to select the group by columns, it will be better if these group by can be selected before hitting the Run query and shown at the end after "Advanced" section after building all the funnel steps. 

2. We also want to have ability to show only selected columns as part of group by properties as shown below.  

3. Have an ability where people can do multiple group by options like 

group by 
Time       Properties 
hr,           selected fields we define like (OS, Platform, City, N/W etc). 
day
week
Month

**Comment by buremba** [comment]
1. Done
2. It's already reported as https://github.com/rakam-io/rakam-ui/issues/64 It's for filters but I extended the issue.
3. It's already reported in https://github.com/rakam-io/rakam/issues/71
Please prefer creating issues for each bug/feature request.
