### ISSUE TITLE
API key page should show proper user specific keys

### ISSUE THREAD

**Issue by sambitdixit** [rakam-io/rakam-ui#69]
i went to Project Settings and then clicked on API. It shows multiple read/write/master keys and then side by side rounded green symbol, red colored revoke button. How do i know which key is for which user ? It should show user email, api keys, status and then action button. 

Admin may by mistake revoke some one's key and then we will struggle to figure out who has done and which users key is revoked etc. All these audit i hope you maintain to trace.

**Comment by sambitdixit** [comment]
@buremba any updates on this ?

**Comment by buremba** [comment]
Added
