### ISSUE TITLE
Funnel UI Hangs When loading large data sets 

### ISSUE THREAD

**Issue by sambitdixit** [rakam-io/rakam-ui#72]
Tried to build a funnel with 5 steps, selected group by dt-hr for 2 days and the no of rows returned would be 100. The query get finished 15 seconds in presto where as UI keeps loading and eventually gives up.  

We need to find a better way to ensure the UI loading is smooth and if data size is bigger than some threshold, better to display the data as table grid and on top corner we can show option to render appropriate graph/chart. The charting components need to be battle tested with large (more than 100 records data set).

**Comment by sambitdixit** [comment]
@buremba Did you get a chance to look at this ?

**Comment by buremba** [comment]
I disabled the chart when there are too many group keys.
