### ISSUE TITLE
Ability to edit already saved funnel 

### ISSUE THREAD

**Issue by sambitdixit** [rakam-io/rakam-ui#73]
I saved a funnel with some conditions and funnel steps. I would like to edit this saved funnel, remove some conditions and add some different conditions e.g. change group by drop down value to a different value (not filter drop down), since the group by is shown only after the query is executed, i dont have any option to edit and change the group by dropdown and want to change it rather than deleting the funnel and recreating again.  Currently there is no choice of editing a saved funnel.

**Comment by buremba** [comment]
I added an option to edit the funnels
