### ISSUE TITLE
User timezone preference is not getting saved.

### ISSUE THREAD

**Issue by RameshByndoor** [rakam-io/rakam-ui#77]
User timezone preference is not getting saved in UI. Following the Screenshot for the same.

<img width="692" alt="screen shot 2017-06-13 at 12 27 10 pm" src="https://user-images.githubusercontent.com/3341964/27069717-b5a92b22-5033-11e7-88c9-4a61bd9decb7.png">

**Comment by buremba** [comment]
It looks like if you're not the owner of the project, you can't change the timezone. I updated it to allow people who have master permission and also fix the bug if you're not authorized.

**Comment by RameshByndoor** [comment]
Project admins should be able to do this. It's not a better practice to do it only by one who created. also no message shown for unauthorized. Always it shows `Successfully saved!`

**Comment by buremba** [comment]
It looks like I didn't push the fix to the Github yet. Could you please test it again for me?

**Comment by sambitdixit** [comment]
How do i know what i saved is the actually the one. Ideally once i saved and come back later, it should show the saved one as pre selected in dropdown. This is not the behaviour after deploying latest changes.

**Comment by buremba** [comment]
Ah, I did a test with the user who is the owner of the project but it looks like if the user is not the owner and have master permission, the issue still occurs. The latest commit should fix the problem, sorry for the trouble.
