### ISSUE TITLE
Navigating Saved Funnels Inconsistent Behaviour

### ISSUE THREAD

**Issue by sambitdixit** [rakam-io/rakam-ui#78]
Step  - I clicked on a saved funnel, then came back and clicked on second saved funnel. 

The behaviour is very inconsistent and shows different things different times. Ramesh also tested the same and it is happening for him as well. 

I have attached the screenshots. 

<img width="1075" alt="screen shot 2017-06-13 at 12 08 02 pm" src="https://user-images.githubusercontent.com/1338801/27072270-8d6701ac-503d-11e7-85ee-850045af352c.png">
<img width="1075" alt="screen shot 2017-06-13 at 12 08 19 pm" src="https://user-images.githubusercontent.com/1338801/27072273-8db61a94-503d-11e7-8f11-6d36bb9b0818.png">
<img width="1164" alt="screen shot 2017-06-13 at 12 09 12 pm" src="https://user-images.githubusercontent.com/1338801/27072274-8dbcbf66-503d-11e7-9c13-a40c50f8110b.png">

**Comment by buremba** [comment]
If the report has dimension, it was trying to run the funnel query. I updated it to run only when the date range is changed.

**Comment by sambitdixit** [comment]
It is still happening. I did a deploy now and still seeing the incosistencies of results shown on click of each saved funnel link. It shows the graphs of old or first time clicked saved funnel data or some times it shows some other saved funnel data. The required behaviour should be 

1. On click of a saved funnel - Show saved funnel data as is (where the steps, filters, date range, groupby should come repopulated and show the saved result for that selected funnel steps and criteria). 
2. The saved funnels can then be edited by changing date range and run Query button and see the new results and then show Save button again, on click of the save button ask in Popup Do you want to replace existing saved funnel named "XX" or create a new saved funnel. 

Attached screenshots 

<img width="1362" alt="screen shot 1" src="https://user-images.githubusercontent.com/1338801/27115783-a027dfe8-50ea-11e7-8816-ac219efeda88.png">
<img width="1364" alt="screen shot 2" src="https://user-images.githubusercontent.com/1338801/27115782-a024d974-50ea-11e7-9a9b-0c9559593ccb.png">
<img width="1356" alt="screen shot 3" src="https://user-images.githubusercontent.com/1338801/27115781-a01e782c-50ea-11e7-9158-2efdef33ee12.png">
<img width="1369" alt="screen shot 4" src="https://user-images.githubusercontent.com/1338801/27115784-a0291d5e-50ea-11e7-8cef-a95af2add404.png">
