### ISSUE TITLE
Report playground: Filters on timestamp doesn't work.

### ISSUE THREAD

**Issue by RameshByndoor** [rakam-io/rakam-ui#79]
When timestamp filters are added it doesn't build the query properly.

Sample query
 ```
SELECT
     "app_timestamp"
   , "app_version"
   , "batch_event_id"
   , "event_name"
   , "nw_type"
   , "os"
   , "platform"
   , "session_id"
   , "tenant"
   , "user_id"
   , "meta_id"
   , "meta_timestamp"
   , "dt_hr"
   , "demand_id"
   , "city"
   , "dt"
   , "hr"
   FROM
     rakam_raptor."events_sdk"."app_launch_v1"
   WHERE ("app_timestamp" < TIMESTAMP '2017-06-13T18:30:00.000Z')
 LIMIT 1000
```

<img width="1087" alt="screen shot 2017-06-13 at 3 40 50 pm" src="https://user-images.githubusercontent.com/3341964/27077767-d07eb30c-504e-11e7-9e5d-2d7f6af6183c.png">

**Comment by RameshByndoor** [comment]
Also look at the time in highlight. There should be provision to get the time value. This must be datetime control rather a date control widget.

**Comment by buremba** [comment]
You're right, it should be date. Fixed.
