### ISSUE TITLE
Geo Cluster Map is working in SQL query page but not working on report or dashboard page (urgent)

### ISSUE THREAD

**Issue by Himmetk** [rakam-io/rakam-ui#8]
My query turn the results on query page on geo cluster map but after I saved it as a report, not working on report or dashboard page.
![screen shot 2016-12-16 at 11 48 39](https://cloud.githubusercontent.com/assets/24540700/21256990/22519cb6-c37e-11e6-9a3d-8f33ddaf1163.png)
![screen shot 2016-12-16 at 11 49 48](https://cloud.githubusercontent.com/assets/24540700/21256991/2256a7ba-c37e-11e6-8022-9aaa990ddf97.png)

**Comment by buremba** [comment]
Fixed.
