### ISSUE TITLE
Funnel graph does not fit all the time when you resize report on dashboard page

### ISSUE THREAD

**Issue by Himmetk** [rakam-io/rakam-ui#84]

**Comment by Himmetk** [comment]
@buremba  also cash issue

**Comment by buremba** [comment]
@Himmetk what was the cash issue?

**Comment by buremba** [comment]
Could you please share the dashboard url with me? I couldn't reproduce the issue.

**Comment by buremba** [comment]
Still waiting for the dashboard url.

**Comment by buremba** [comment]
@Himmetk Still waiting for the dashboard url. :)

**Comment by Himmetk** [comment]
sorry, I forgot this I cannot reproduce the issue cause I removed the dashboard.

**Comment by buremba** [comment]
OK then, I'm closing the issue. Feel free to create or reopen if you see the bug again.
