### ISSUE TITLE
Use of Variables in Custom Query Section of Parameter Options

### ISSUE THREAD

**Issue by Hosssman** [rakam-io/rakam-ui#91]
![ekran resmi 2017-06-23 10 11 52](https://user-images.githubusercontent.com/29651120/27470412-6dd76fa4-57fc-11e7-91c2-c3da78ed3ecd.png)

Please see the picture attached.
This example  query written inside the custom query box pulls all the distinct coupon codes in the database. However there are 9million distinct coupon entries in our database. Thus we would like to filter our selection over the recent dates with a WHERE clause. For this filtering we would like to use the Date variable we created inside our main SQL code.

**Comment by buremba** [comment]
Implemented
