### ISSUE TITLE
Simple Date Format

### ISSUE THREAD

**Issue by Hosssman** [rakam-io/rakam-ui#95]
We can edit date display format in settings but when we export the data, we are getting date columns as the most detailed format. 

We couldn't find a way to make the date column more simple. We have tried to use to_timestamp (date, 'dd mon yyyy') or similar syntax we found from the internet inside the query but they don't work. 

Can we have a document for all format types or how we can edit them,

What's your advice on this?

Thanks

**Comment by buremba** [comment]
I changed the behaviour of export feature, now it should include the formatted values of columns. It should solve your problem.
