### ISSUE TITLE
Turkish Characters in Fields

### ISSUE THREAD

**Issue by Hosssman** [rakam-io/rakam-ui#98]
When we try to filter or write a query as a dimension while we select from DB fields containing non-english characters, we are facing this issue. 

https://app.rakam.io/557/reports/haftalik_satislar

You can select a dimension with Turkish characters to see what's wrong

Thanks

**Comment by buremba** [comment]
It looks like the report is deleted. Could you please reproduce the issue with a new report and share the link with me?

**Comment by Hosssman** [comment]
Hello,

Here is an example report;

https://app.rakam.io/557/reports/muhasebe_satis_iade_son_marka

There is m.label being used as dimenson. When we pick Biondina as dimension (As default)  there is no problem. 

But when we pick Didem'in İzi, It gives an error. 

String becomes something like 'Didem''in \0130zi'

Do we need to avoid using columns which can contain non english characters as dimensions?

**Comment by buremba** [comment]
Fixed.
